### ISSUE TITLE
Symfonisk Controller E1744 - working

### ISSUE THREAD

**Issue by crmunro** [xaviml/z2m_ikea_controller#8]
Hi there! 

Great plugin, thank you - saved me a lot of time and frustration. I just wanted to report that the Symfonisk controller, E1744, works quite well with this automation. It's not quite perfectly smooth dimming, but it's close enough for my purposes. 

I think you could update your table to include the following; bearing in mind that the E1744 doesn't have the same 'rotate_x_quick' actions that the ICTC-G-1 has: 

Model 		| Controller type 	| Class				| Actions
ICTC-G-1 	| Light 			| ICTCG1Controller 	| rotate_left, rotate_right, rotate_stop

You could optionally update the code to differentiate the Controller class, however the E1744 controller works fine with the ICTC-G-1 class.

Thanks again!

**Comment by xaviml** [comment]
Hi @crmunro 

I recently got a symfonisk controller, but I haven't started playing with it. I was thinking to support light and media_player with it. I will keep you updated on it.

**Comment by xaviml** [comment]
Hey @crmunro,

I just released a new code with support for the E1744 as light or media player. Check the device support and the controller type in the [wiki](https://github.com/xaviml/z2m_ikea_controller/wiki).
Here is an example to control your light with the E1744:
```yaml
test:
  module: z2m_ikea_controller
  class: E1744LightController
  sensor: <your action sensor>
  light: <your light>
```

I tried the E1744 with z2m without the recommended debounce option and it worked quite well. If I leave the debounce then the state will remain on the home assistant instead of leaving blank again.
You can do the following with the controller:
- 1 click to toggle the light (on/off)
- 2 clicks to put the light on full brightness
- Rotate the controller left/right for volume down/up

Let me know if this works well for you too.

**Comment by tobimori** [comment]
@xaviml Thanks for the update! I tried using it, but I can't get it to work without bugs (Media Player only, haven't tested Lights).

When trying to pause using the controller, it pauses for half a second, then starts again.

**Comment by xaviml** [comment]
Hi @tobimori 

Thanks for your feedback! I got it working without the `debounce` option since when I had it on, it was quite buggy. Which device are you trying it on? I read yesterday there is a bug on z2m for this controller that sends the commands twice. Can you check if when you click you see "play_pause" twice in the z2m logs? I do have them, but it works okay with Google Home mini.

**Comment by tobimori** [comment]
@xaviml nope, not sending it twice. using a cca.

**Comment by xaviml** [comment]
So is your problem just the play_pause when debounce is not included? Does the volume work as expected?

**Comment by tobimori** [comment]
@xaviml Yea.

**Comment by xaviml** [comment]
@tobimori I added a simple logic that does not allow to call an action that has been called within a small period of time. The changes are in the master branch. You can either:
- Select `master` from HACS on the Z2M Ikea Controller app
- Copy and paste the file z2m_ikea_controller.py into /config/appdaemon/apps/z2m_ikea_controller/z2m_ikea_controller.py

Let me know if this fixed your problem. Thank you for your collaboration.

**Comment by tobimori** [comment]
@xaviml Works really well, thanks for the fast fix!
